'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { Check, ChevronDown, Download, Eraser, FileUp, Highlighter, Keyboard, MousePointer2, PenLine, Redo2, RotateCcw, Sparkles, Undo2 } from 'lucide-react';
import { PDFDocument, rgb } from 'pdf-lib';

type Tool = 'select'|'pen'|'marker'|'x'|'eraser';
type Stroke = 'solid'|'dashed'|'dotted';
type Point = {x:number;y:number};
type Mark = {id:string;type:'pen'|'marker'|'x';points?:Point[];x?:number;y?:number;color:string;size:number;stroke:Stroke};
const palette=['#1d5a46','#111827','#dc2626','#2563eb','#f59e0b','#8b5cf6'];

export default function Home(){
  const fileRef=useRef<HTMLInputElement>(null),pdfCanvas=useRef<HTMLCanvasElement>(null),surface=useRef<HTMLDivElement>(null);
  const [source,setSource]=useState('/csc_dsa_flowchart.pdf'),[name,setName]=useState('csc_dsa_flowchart.pdf'),[bytes,setBytes]=useState<Uint8Array|null>(null);
  const [tool,setTool]=useState<Tool>('pen'),[color,setColor]=useState('#1d5a46'),[size,setSize]=useState(5),[stroke,setStroke]=useState<Stroke>('solid'),[marks,setMarks]=useState<Mark[]>([]),[redo,setRedo]=useState<Mark[]>([]),[draft,setDraft]=useState<Mark|null>(null),[zoom,setZoom]=useState(76),[ready,setReady]=useState(false);

  const loadPdf=useCallback(async(url:string,data?:Uint8Array)=>{setReady(false);const pdfjs=await import('pdfjs-dist');pdfjs.GlobalWorkerOptions.workerSrc='/pdf.worker.min.mjs';const raw=data||new Uint8Array(await (await fetch(url)).arrayBuffer());setBytes(raw);const doc=await pdfjs.getDocument({data:raw.slice()}).promise,page=await doc.getPage(1),viewport=page.getViewport({scale:2});const c=pdfCanvas.current;if(!c)return;c.width=viewport.width;c.height=viewport.height;await page.render({canvasContext:c.getContext('2d')!,viewport}).promise;setReady(true)},[]);
  useEffect(()=>{loadPdf(source)},[source,loadPdf]);

  async function importPdf(file:File){if(!file.name.toLowerCase().endsWith('.pdf'))return;const data=new Uint8Array(await file.arrayBuffer());setName(file.name);setMarks([]);setRedo([]);setSource(URL.createObjectURL(file));await loadPdf('',data)}
  function point(e:React.PointerEvent){const r=surface.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
  function start(e:React.PointerEvent){if(tool==='select')return;const p=point(e);if(tool==='x'){add({id:crypto.randomUUID(),type:'x',x:p.x,y:p.y,color,size,stroke});return}if(tool==='eraser'){eraseAt(p);return}e.currentTarget.setPointerCapture(e.pointerId);setDraft({id:crypto.randomUUID(),type:tool as 'pen'|'marker',points:[p],color,size,stroke})}
  function move(e:React.PointerEvent){if(!draft)return;setDraft(d=>d?{...d,points:[...(d.points||[]),point(e)]}:null)}
  function end(){if(!draft)return;add(draft);setDraft(null)}
  function add(mark:Mark){setMarks(m=>[...m,mark]);setRedo([])}
  function eraseAt(p:Point){let nearest=-1,dist=.06;marks.forEach((m,i)=>{const pts=m.points||[{x:m.x||0,y:m.y||0}];pts.forEach(q=>{const d=Math.hypot(q.x-p.x,q.y-p.y);if(d<dist){nearest=i;dist=d}})});if(nearest>=0)setMarks(m=>m.filter((_,i)=>i!==nearest))}
  function undo(){const last=marks.at(-1);if(!last)return;setMarks(m=>m.slice(0,-1));setRedo(r=>[last,...r])}
  function doRedo(){const first=redo[0];if(!first)return;setMarks(m=>[...m,first]);setRedo(r=>r.slice(1))}
  useEffect(()=>{function keys(e:KeyboardEvent){const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?doRedo():undo();return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();doRedo();return}if(e.key==='+'||e.key==='='){e.preventDefault();setZoom(z=>Math.min(110,z+8));return}if(e.key==='-'){e.preventDefault();setZoom(z=>Math.max(45,z-8));return}if(e.key==='Escape'||e.key.toLowerCase()==='v')setTool('select');if(e.key.toLowerCase()==='p')setTool('pen');if(e.key.toLowerCase()==='m')setTool('marker');if(e.key.toLowerCase()==='x')setTool('x');if(e.key.toLowerCase()==='e')setTool('eraser')}window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys)},[marks,redo]);
  async function exportPdf(){if(!bytes||!pdfCanvas.current)return;const doc=await PDFDocument.create(),width=792,height=612,page=doc.addPage([width,height]),background=await doc.embedPng(pdfCanvas.current.toDataURL('image/png'));page.drawImage(background,{x:0,y:0,width,height});for(const m of marks){const c=hex(m.color),dash=m.stroke==='dashed'?[m.size*2,m.size*1.4]:m.stroke==='dotted'?[m.size*.25,m.size*1.35]:undefined;if(m.type==='x'){const x=(m.x||0)*width,y=height-(m.y||0)*height,s=m.size*3.4;page.drawLine({start:{x:x-s,y:y-s},end:{x:x+s,y:y+s},thickness:Math.max(2,m.size*.8),color:rgb(c[0],c[1],c[2])});page.drawLine({start:{x:x-s,y:y+s},end:{x:x+s,y:y-s},thickness:Math.max(2,m.size*.8),color:rgb(c[0],c[1],c[2])})}if(m.points&&m.points.length>1)for(let i=1;i<m.points.length;i++){const a=m.points[i-1],b=m.points[i];page.drawLine({start:{x:a.x*width,y:height-a.y*height},end:{x:b.x*width,y:height-b.y*height},thickness:m.type==='marker'?m.size*3:m.size*.75,color:rgb(c[0],c[1],c[2]),opacity:m.type==='marker'?.28:1,dashArray:dash})}}const blob=new Blob([await doc.save() as BlobPart],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/\.pdf$/i,'')+'-marked.pdf';a.click();URL.revokeObjectURL(url)}
  const allMarks=draft?[...marks,draft]:marks;
  return <main className="flow-app"><input ref={fileRef} hidden type="file" accept="application/pdf" onChange={e=>e.target.files?.[0]&&importPdf(e.target.files[0])}/>
    <header className="flow-top"><div className="flow-brand"><div className="logo"><span/><span/></div><b>Pathmark</b></div><div className="file-name"><div><strong>{name}</strong><small>{marks.length} mark{marks.length===1?'':'s'} · saved on this device</small></div><ChevronDown size={15}/></div><div className="head-actions"><button className="quiet" onClick={()=>fileRef.current?.click()}><FileUp size={16}/>Change flowchart</button><button className="primary" onClick={exportPdf}><Download size={16}/>Export marked PDF</button></div></header>
    <section className="flow-body"><aside className="toolrail"><div className="rail-label">TOOLS</div><ToolButton label="Select" shortcut="V" icon={<MousePointer2/>} active={tool==='select'} onClick={()=>setTool('select')}/><ToolButton label="Pen" shortcut="P" icon={<PenLine/>} active={tool==='pen'} onClick={()=>setTool('pen')}/><div className="pen-quick" aria-label="Pen color and stroke size"><input aria-label="Pen color" title="Pen color" type="color" value={color} onChange={e=>setColor(e.target.value)}/><input aria-label="Pen stroke size" title={`Stroke size ${size}`} type="range" min="2" max="14" value={size} onChange={e=>setSize(+e.target.value)}/></div><ToolButton label="Marker" shortcut="M" icon={<Highlighter/>} active={tool==='marker'} onClick={()=>setTool('marker')}/><ToolButton label="" title="Cross out class" shortcut="X" icon={<span className="x-icon">×</span>} active={tool==='x'} onClick={()=>setTool('x')}/><ToolButton label="Eraser" shortcut="E" icon={<Eraser/>} active={tool==='eraser'} onClick={()=>setTool('eraser')}/><div className="rail-spacer"/><button className="history" title="Undo (⌘Z)" onClick={undo} disabled={!marks.length}><Undo2/></button><button className="history" title="Redo (⇧⌘Z)" onClick={doRedo} disabled={!redo.length}><Redo2/></button></aside>
      <section className="board"><div className="board-top"><div><b>Computer Science Degree Plan</b><span>Mark completed classes, add notes, and plan what comes next.</span></div><div className="zoom"><button onClick={()=>setZoom(z=>Math.max(45,z-8))}>−</button><span>{zoom}%</span><button onClick={()=>setZoom(z=>Math.min(110,z+8))}>+</button></div></div><div className="board-scroll"><div className="document-wrap" style={{width:`${zoom}%`}}><div ref={surface} className={`document tool-${tool}`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end}><canvas ref={pdfCanvas}/>{ready&&<svg className="ink-layer" viewBox="0 0 1000 772" preserveAspectRatio="none">{allMarks.map(m=><MarkView key={m.id} mark={m}/>)}</svg>}{!ready&&<div className="loading"><RotateCcw/>Loading flowchart…</div>}</div></div></div></section>
      <aside className="options"><div className="options-head"><div><Sparkles size={16}/><b>{tool==='x'?'Options':tool[0].toUpperCase()+tool.slice(1)+' options'}</b></div><span>LIVE</span></div><div className="option-block"><label>COLOR</label><div className="swatches">{palette.map(p=><button key={p} onClick={()=>setColor(p)} className={color===p?'picked':''} style={{background:p}}>{color===p&&<Check/>}</button>)}<input aria-label="Custom color" type="color" value={color} onChange={e=>setColor(e.target.value)}/></div><div className="hex"><span style={{background:color}}/><code>{color.toUpperCase()}</code></div></div><div className="option-block"><div className="size-title"><label>STROKE SIZE</label><b>{size}</b></div><input type="range" min="2" max="14" value={size} onChange={e=>setSize(+e.target.value)}/><div className="size-preview"><span className={stroke} style={{height:Math.max(2,size*.8),color,background:stroke==='solid'?color:undefined}}/><small>Preview</small></div></div>{(tool==='pen'||tool==='marker')&&<div className="option-block"><label>PEN STROKE</label><div className="stroke-options">{(['solid','dashed','dotted'] as Stroke[]).map(s=><button key={s} className={stroke===s?'active':''} onClick={()=>setStroke(s)}><i className={s}/><span>{s}</span></button>)}</div></div>}<div className="option-block status-card"><div className="status-icon">{tool==='x'?'×':tool==='marker'?'▰':'⌁'}</div><div><b>{tool==='x'?'Click a class to cross it out':tool==='eraser'?'Click a mark to remove it':'Draw directly on the page'}</b><p>{tool==='x'?'The X scales with your selected size. Great for marking completed courses.':'Every mark is included in the exported PDF.'}</p></div></div><div className="shortcuts"><div><Keyboard size={14}/><b>Keyboard shortcuts</b></div><p><kbd>P</kbd> Pen <kbd>M</kbd> Marker <kbd>X</kbd> Cross out <kbd>E</kbd> Eraser</p><p><kbd>⌘Z</kbd> Undo <kbd>⇧⌘Z</kbd> Redo <kbd>+ −</kbd> Zoom</p></div><div className="privacy"><span>◆</span><div><b>Private by design</b><p>Your flowchart stays in your browser. Nothing is uploaded.</p></div></div></aside>
    </section></main>
}
function ToolButton({label,title,shortcut,icon,active,onClick}:{label:string;title?:string;shortcut:string;icon:React.ReactNode;active:boolean;onClick:()=>void}){const name=title||label;return <button className={`tool-button ${active?'active':''}`} aria-label={`${name} (${shortcut})`} title={`${name} (${shortcut})`} onClick={onClick}>{icon}{label&&<span>{label}</span>}<kbd>{shortcut}</kbd></button>}
function MarkView({mark:m}:{mark:Mark}){if(m.type==='x'){const x=(m.x||0)*1000,y=(m.y||0)*772,s=m.size*4.2;return <g stroke={m.color} strokeWidth={Math.max(3,m.size)} strokeLinecap="round"><line x1={x-s} y1={y-s} x2={x+s} y2={y+s}/><line x1={x-s} y1={y+s} x2={x+s} y2={y-s}/></g>}if(!m.points?.length)return null;const dash=m.stroke==='dashed'?`${m.size*2} ${m.size*1.4}`:m.stroke==='dotted'?`${m.size*.25} ${m.size*1.35}`:undefined;return <polyline points={m.points.map(p=>`${p.x*1000},${p.y*772}`).join(' ')} fill="none" stroke={m.color} strokeWidth={m.type==='marker'?m.size*3.2:m.size} strokeOpacity={m.type==='marker'?.3:1} strokeDasharray={dash} strokeLinecap="round" strokeLinejoin="round"/>}
function hex(v:string){return [parseInt(v.slice(1,3),16)/255,parseInt(v.slice(3,5),16)/255,parseInt(v.slice(5,7),16)/255]}
